site:
  title: "Ivan Tikhonov's Blog"
  description: "A collection of post-its I couldn’t have found on the internet"
  url: "https://itikhon0v.github.io"
  author: "Ivan Tikhonov"
  date_format: "%Y-%m-%d"

paths:
  input_dir: "md"
  output_dir: "dist/blog"
  index_template: "templates/index.html"
  post_template: "templates/post.html"
  rss_output: "dist/rss.xml"
  index_output: "dist/index.html"

