site:
  title: "My Humble Blog"
  url: "https://itikhon0v.github.io"
  author: "Ivan Tikhonov"
  date_format: "%Y-%m-%d"

paths:
  input_dir: "dist/md"
  output_dir: "dist/blog"
  index_template: "assets/html/index.html"
  post_template: "assets/html/post.html"
  css_path: "assets/css/style.css"
  rss_output: "dist/rss.xml"
  index_output: "dist/index.html"

